kind: pipeline
type: docker
name: default

steps:
- name: build-service
  image: maven:3.6-jdk-11
  commands:
    - cd service/fling
    - mvn clean package

- name: build-web
  image: node:latest
  commands:
    - ls -al
    - cd web/fling
    - npm install && CI=false npm run build

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: container/Dockerfile
    repo: arminfriedl/fling
    tags: dev
