spring:
  datasource:
    url: jdbc:h2:file:~/Desktop/testdb;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart.max-file-size: -1
    multipart.max-request-size: -1
    
logging.level:
  root: WARN
  net.friedl: TRACE
#  org.springframework.security: TRACE
#  org.springframework: WARN
#  org.hibernate: WARN
# spring.http.log-request-details: true

fling:
  archive.fileystem.directory: "/home/armin/Desktop/fling"
  security:
    allowed-origins:
      - "https://friedl.net"
      - "http://localhost:3000"
      - "http://localhost:5000"
      - "http://10.0.2.2:5000"
    admin-user: "${FLING_ADMIN_USER:admin}"
    admin-password: "${FLING_ADMIN_PASSWORD:123}"
    signing-key: "${FLING_SIGNING_KEY:changeitchangeitchangeitchangeit}"
    jwt-expiration: "${FLING_JWT_EXPIRATION:180000}"