spring:
  datasource:
    url: jdbc:h2:file:~/Desktop/testdb;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart.max-file-size: -1
    multipart.max-request-size: -1

logging.level:
  root: WARN
  net.friedl: TRACE
#  org.springframework.security: TRACE
#  org.springframework: WARN
#  org.hibernate: WARN
# spring.http.log-request-details: true

fling:
  max-artifact-size: 209715200 # 200 MB
  archive.filesystem.archive-path: /home/armin/Desktop/fling
  security:
    allowed-origins:
      - "https://friedl.net"
      - "http://localhost:3000"
      - "http://localhost:5000"
      - "http://10.0.2.2:5000"
    admin-name: "admin"
    admin-password: "123"
    signing-key: "changeitchangeitchangeitchangeit"
    jwt-expiration: "180000"
  api:
    version: "0.1.0-snapshot"
    server-url: "http://localhost:8080"
    server-description: "API server for dev"
