---
openapi: 3.0.2
info:
  title: Fling
  version: 1.0.0
  description: A project based API for publishing and sharing digital artifacts
  contact:
    name: Armin Friedl
    email: dev@friedl.net
paths:
  /fling:
    summary: A fling share
    description: |-
      A grouping of shared objects. Settings for sharing and expiration are
      associated with a fling.
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fling'
          description: List of metadata for all flings
      summary: Get a list of metadata for all flings
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fling'
        required: true
      responses:
        "200":
          description: Fling created successfuly
      summary: Create a new fling
  /fling/{flingId}:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fling'
          description: A fling object containing all metadata of the fling
      summary: Get metadata for a fling
      description: Expiration, sharing and general information of a fling.
    delete:
      responses:
        "200":
          description: Fling deleted successfully
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fling'
        required: true
      parameters:
      - name: id
        description: The unique fling id
        schema:
          format: int64
          type: integer
        in: query
        required: true
      responses:
        "200":
          description: Fling was successfully updated
    parameters:
    - name: flingId
      description: Unique id of the fling
      schema:
        format: int64
        type: integer
      in: path
      required: true
  /f:
    summary: Endpoint for accessing flings by external users
  /f/{shareId}:
    get:
      responses:
        "302":
          content:
            text/html:
              schema:
                type: string
          description: |-
            If the fling is marked as direct download, the user will be directly redirected
            to /f/{sharId}/download which starts the fling download.
        "200":
          content:
            application/json: {}
          description: sdf
    parameters:
    - name: shareId
      description: |-
        A share id with which a fling can be uniquely identified. The share id might be
        the fling id also used in /fling endpoints, another artificially generated id or
        a customURL given by the fling creator
      schema:
        type: string
      in: path
      required: true
  /fling/{flingId}/artifact:
    summary: Upload an object to the fling identified by id
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artifact'
          description: A list of metadata of all objects within this fling
      summary: Retrieve a list of metadata all objects within this fling
    post:
      requestBody:
        description: "Content type is any media type from \nhttps://www.iana.org/assignments/media-types/media-types.xhtml.\n\
          The content can by arbitrary payload and will be stored as-is."
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
        required: true
      parameters:
      - name: name
        description: The name of the object
        schema:
          type: string
        in: query
        required: true
      - name: path
        description: |-
          A path under which the object should be stored. Nested paths must be delimited
          by forward slash '/'. The path might or might not start with a '/', it will always
          be interpreted as absolute starting from the fling root.
        schema:
          type: string
        in: query
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artifact'
          description: Return the metadata of a fling object after successful request
    parameters:
    - name: flingId
      description: Unique id for the fling
      schema:
        format: int64
        type: integer
      in: path
      required: true
  /fling/{flingId}/artifact/{objectId}:
    summary: Endpoint for interacting with individual objects within a fling
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artifact'
          description: Return the metadata of a fling object after successful request
      summary: Retrive the metadata of an object within a fling
    put:
      requestBody:
        description: "Content type is any media type from \nhttps://www.iana.org/assignments/media-types/media-types.xhtml.\n\
          The content can by arbitrary payload and will be stored as-is."
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artifact'
          description: Return the metadata of a fling object after successful request
      summary: Create a new version of the object
    parameters:
    - name: flingId
      description: The unique id of the fling
      schema:
        format: int64
        type: integer
      in: path
      required: true
    - name: objectId
      description: |-
        The unique id of the object within its fling. The id is not necessarily globally
        unique across all flings.
      schema:
        format: int64
        type: integer
      in: path
      required: true
components:
  schemas:
    Fling:
      description: |-
        Fling containing all metadata of a fling, including general information,
        sharing settings and expiration settings.
      required:
      - name
      type: object
      properties:
        name:
          description: Human readable name of the fling
          type: string
        id:
          format: int64
          description: Unique id of the fling
          type: integer
        expiration:
          description: Expiration settings
          type: object
          properties:
            expirationType:
              description: Expiration type
              enum:
              - Time
              - Clicks
              type: string
            value:
              description: Parsable string representation for the expiration type
              type: string
        sharing:
          description: Settings for sharing
          type: object
          properties:
            directDownload:
              description: Accessing the share will immediately prompt a download
              type: boolean
            upload:
              description: Allow external users to upload to the share
              type: boolean
            customURL:
              description: |-
                Makes the fling available under a custom URL. The URL is only
                allowed to have one path element. The allowed characters are
                [A-Za-z0-9-._~], that is, the unreserved URL characters of
                https://www.ietf.org/rfc/rfc3986 excluding the forward
                slash. The customURL must be unique across all flings
                of a Fling application deployment.
              type: string
    Artifact:
      description: An object in a fling share
      required:
      - name
      - doi
      type: object
      properties:
        name:
          description: The name of the object
          type: string
        id:
          format: int64
          description: The unique id of the object within its fling
          type: integer
        path:
          description: |-
            The path of the object within its fling. Nested paths are separated by a forward
            slash '/'. A path may or may not start with '/'. A path will always be interpreted
            as absolute with the fling of the object as root.
          type: string
        doi:
          description: "A unique and stable id for the fling object. This id is unique\
            \ across all flings\nand versions of an object within a Fling deployment.\
            \ A doi is never assigned twice\nby a Fling deployment, even if the object\
            \ it referred to (or a version thereof) \nwas delted. A doi might not\
            \ resolve to an object if the object was deleted."
          type: string
        version:
          description: The version of the object
          type: integer
        fling:
          format: int64
          description: The id of the fling this object belongs to
          type: integer
